// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Monklongpae.Models
{
    public partial class Account
    {
        public int IdAccount { get; set; }
        public string NameAccout { get; set; }
        public string Account1 { get; set; }
        public int? AccountStatus { get; set; }
    }
}