// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Monklongpae.Models
{
    public partial class Contact
    {
        public int IdContact { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public string Map { get; set; }
    }
}