// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Monklongpae.Models
{
    public partial class History
    {
        public int IdHistory { get; set; }
        public int? IdVideo { get; set; }
        public int? IdUser { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}