// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Monklongpae.Models
{
    public partial class Market
    {
        public int IdMarket { get; set; }
        public int? IdVideo { get; set; }
        public string Url { get; set; }
        public double? Duration { get; set; }
        public DateTime? CreateAt { get; set; }
        public string PartImage { get; set; }
        public double? Showtime { get; set; }
    }
}