// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Monklongpae.Models
{
    public partial class NameVideo
    {
        public int IdNameVideo { get; set; }
        public int? IdCatory { get; set; }
        public string Name { get; set; }
        public DateTime? CreateDate { get; set; }
        public string PathDisplay { get; set; }
    }
}