// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Monklongpae.Models
{
    public partial class Packet
    {
        public int IdPacket { get; set; }
        public string Name { get; set; }
        public string Day { get; set; }
        public int? Price { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
    }
}