// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Monklongpae.Models
{
    public partial class PageMessage
    {
        public int IdPage { get; set; }
        public string MessagePage1Th { get; set; }
        public string MessagePage1En { get; set; }
        public string MessagePage2Th { get; set; }
        public string MessagePage2En { get; set; }
        public string MessagePage3Th { get; set; }
        public string MessagePage3En { get; set; }
        public string MessagePage4Th { get; set; }
        public string MessagePage4En { get; set; }
    }
}