// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Monklongpae.Models
{
    public partial class Payment
    {
        public int IdPayment { get; set; }
        public string FilePayment { get; set; }
        public string Status { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public int? IdUser { get; set; }
        public int? IdPacket { get; set; }
        public bool? Isactive { get; set; }
    }
}