// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Monklongpae.Models
{
    public partial class User
    {
        public int IdUser { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string Tel { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public int? IdRole { get; set; }
        public string ImagePath { get; set; }
        public DateTime? PacketDateLimit { get; set; }
        public bool? Isactive { get; set; }
        public bool? OnlineStatus { get; set; }
        public DateTime? WorkDate { get; set; }
        public string Token { get; set; }
        public string MacAddress { get; set; }
        public bool? IsOnline { get; set; }
    }
}