// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Monklongpae.Models
{
    public partial class Video
    {
        public int IdVideo { get; set; }
        public string PathVideo { get; set; }
        public int? IdNameVideo { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Views { get; set; }
        public string PathDisplay { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string TimeVideo { get; set; }
        public int? LimitVideoUser { get; set; }
    }
}