// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Monklongpae.Models
{
    public partial class VideoPage
    {
        public int IdVideoPage { get; set; }
        public string Path { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}